<a href="https://colab.research.google.com/github/Feliperojas2601/MetNumUN2022II/blob/main/Quiz6/Group27_Quiz6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Group 27 Quiz 6

In [2]:
import pandas as pd 

data = {
    'LMA': [200, 200, 200, 150, 150, 150, 100, 100, 100], 
    'SMA': [20, 5, 10, 20, 5, 10, 20, 5 , 10], 
    'R6M': [0.20076577467416873, 0.20076577467416873, 0.20076577467416873, 0.20076577467416873, 
            0.20076577467416873, 0.20076577467416873, -0.1318338094263914, -0.1674692310077511, -0.12917858006448477], 
    'R2Y': [-1.0630960949507189, -1.0802249988501094, -1.141725638487146, -0.7823882991874737, 
            -0.8450057737866599, -0.8742241591454335, -0.8950632731460907, -0.9970043823939182, -1.0182385633196027]
}

df = pd.DataFrame(data)
df['AR'] = (df['R2Y'] + df['R6M'])/2
df = df.sort_values(by = ['AR'], ascending = False)
df

   LMA  SMA       R6M       R2Y        AR
3  150   20  0.200766 -0.782388 -0.290811
4  150    5  0.200766 -0.845006 -0.322120
5  150   10  0.200766 -0.874224 -0.336729
0  200   20  0.200766 -1.063096 -0.431165
1  200    5  0.200766 -1.080225 -0.439730
2  200   10  0.200766 -1.141726 -0.470480
6  100   20 -0.131834 -0.895063 -0.513449
8  100   10 -0.129179 -1.018239 -0.573709
7  100    5 -0.167469 -0.997004 -0.582237